services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

  redis:
    image: redis:7-alpine
    #Redis поднят с паролем
    command: ["redis-server", "--requirepass", "secret"]

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    build: ./backend
    env_file: .env
    environment:
      PORT: 3000
      ENV_FILE: /app/host/.env
    ports:
      - "8080:3000"
    volumes:
      - ./backend/src:/app/src
      - ./frontend:/app/public
      - ./:/app/host:ro
    depends_on:
      - postgres
      - redis
      - mongo
